# Generated by Django 5.1.1 on 2024-09-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
    ]
