# Generated by Django 5.1.1 on 2024-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_customuser_is_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Role',
            field=models.CharField(default='buyer', max_length=10),
        ),
    ]
